# Generated by Django 3.1.7 on 2021-03-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='quantity',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
